### ISSUE TITLE
[ERROR] Shader either doesn't exist or doesn't have the PublicAPI flag set 

### ISSUE THREAD

**Issue by plasmalasgun** [dfranx/PluginShadertoy#2]
[ERROR] Shader either doesn't exist or doesn't have the PublicAPI flag set

**Comment by dfranx** [comment]
Yeah, some shaders can't be accessed through the Shadertoy's API.

**Comment by ghmart** [comment]
Still doesn't work.

Tried different SHADERed versions (binary releases and compiled from source)
Tried many different examples, including "Happy Jumping" (https://www.shadertoy.com/view/3lsSzf)

Systems: Xubuntu, Debian

**Comment by dfranx** [comment]
Use the latest version of SHADERed and the latest version of ShadertoyImport plugin (you could try compiling the plugin from the source).
It should work fine. Here's the "Happy jumping":
![Shadertoy](https://user-images.githubusercontent.com/30801537/101289451-db920c00-37fc-11eb-9ab5-f12f6c726ce7.gif)

**Comment by ghmart** [comment]
Tried with SHADERed binary 1.4.2 and ShadertoyImport binary dated 2020-07-27 with no luck.
Maybe it's ok on Windows. I cannot check (SHADERed asks for some vcredist dll).
I suspect that same error will appear on any fresh installed Debian-based distribution.
Maybe it's ok on your development machine and my system lacking some shared library or environment setup?

**Comment by dfranx** [comment]
Hmm I'll check it out on my Ubuntu later.
BTW for that issue on Windows, you must install vcredist: [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe) or [vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe). 
But I'll test it out later and see what's going on.

**Comment by ghmart** [comment]
Thank you!
Windows version works (installed version of vc_redist from the link you provided) (Windows 7 64-bit).

By the way, it's so horrible situation with all those vc redist packages - many applications comes with their own version. My installation already has good dozen of them:
![vcredist](https://user-images.githubusercontent.com/7192155/101368659-d7c7bd80-38c0-11eb-9e91-935b5bf662e5.png)

Your application is cool! Hope to see SHADERed & ShadertoyImporter working in my Debian system.

**Comment by dfranx** [comment]
Thank you! I actually think I know what causes the issue on Linux... I think I compiled the plugin without providing the ShaderToy API key ( https://github.com/dfranx/PluginShadertoy/blob/master/APIKey.h )... I'll update it either today or tomorrow.

**Comment by ghmart** [comment]
Any progress on this?

**Comment by ghmart** [comment]
OK, I registered on ShaderToy to get my own API key, but didn't found were it can be requested. Their documentation states "Request Your Key" - "Click here to access your Apps or via your Profile" - "After you request your API Key..." I can't find how to request that key. No button to "request" it.

**Comment by mkohlhaas** [comment]
Having the same problem under Void Linux. Compiled SHADERed and the Shadertoy plugin. I checked out the latest version for each. This is what I get from gdb when I hit the OK button when trying to import the Happy Jumping project from Shadertoys:

``````
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff76eb536 in __GI_abort () at abort.c:79
#2  0x00007ffff7948827 in ?? () from /usr/lib/libstdc++.so.6
#3  0x00007ffff7976bd6 in ?? () from /usr/lib/libstdc++.so.6
#4  0x00007ffff7976c41 in std::terminate() () from /usr/lib/libstdc++.so.6
#5  0x00007ffff7976ed4 in __cxa_throw () from /usr/lib/libstdc++.so.6
#6  0x00007ffff794b51f in std::__throw_system_error(int) () from /usr/lib/libstdc++.so.6
#7  0x0000555556239da5 in std::recursive_mutex::lock (this=0x7ffff1fbf560) at /usr/include/c++/10.2/mutex:110
#8  0x000055555625035c in std::lock_guard<std::recursive_mutex>::lock_guard (this=0x7fffffff3d90, __m=...) at /usr/include/c++/10.2/bits/std_mutex.h:159
#9  0x0000555556246e87 in httplib::ClientImpl::send (this=0x7ffff1fbf4e0, req=..., res=..., error=@0x7fffffff3e64: httplib::Success) at /home/schmidh/Gitrepos/SHADERed/libs/misc/httplib.h:5293
#10 0x000055555624788e in httplib::ClientImpl::send_ (this=0x7ffff1fbf4e0, req=...) at /home/schmidh/Gitrepos/SHADERed/libs/misc/httplib.h:5388
#11 0x0000555556249cb8 in httplib::ClientImpl::Get(char const*, std::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, httplib::detail::ci, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::function<bool (unsigned long, unsigned long)>) (this=0x7ffff1fbf4e0, path=0x555559277c70 "/api/v1/shaders/3lsSzf?key=NdrKM1",
    headers=..., progress=...) at /home/schmidh/Gitrepos/SHADERed/libs/misc/httplib.h:5843
#12 0x0000555556249b66 in httplib::ClientImpl::Get (this=0x7ffff1fbf4e0, path=0x555559277c70 "/api/v1/shaders/3lsSzf?key=NdrKM1") at /home/schmidh/Gitrepos/SHADERed/libs/misc/httplib.h:5824
#13 0x000055555624a561 in httplib::Client::Get (this=0x7fffffff4860, path=0x555559277c70 "/api/v1/shaders/3lsSzf?key=NdrKM1") at /home/schmidh/Gitrepos/SHADERed/libs/misc/httplib.h:7112
#14 0x00007ffff1dfc06b in ?? ()
#15 0x00007fffffff4bd0 in ?? ()
#16 0x00007fffffff4bb0 in ?? ()
#17 0x41ed645d3f800000 in ?? ()
#18 0x0000004e00000034 in ?? ()
#19 0x40fb9b4d0000059d in ?? ()
#20 0x0000000000000000 in ?? ()

(You can see my Shadertoy API key in there actually. But I don't care.)

What could I do to actually debug it more thoroughly?
